import type { Metadata } from "next";
import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { OPERATOR, SUPPORT_EMAIL, POLICY_UPDATED } from "@/lib/site";
export const metadata: Metadata = { title: 'Privacy notice', description: 'How Soulscope Technologies handles account information, voice recordings, saved results, and privacy requests in the SoulScope beta.', alternates: { canonical: "/privacy" } };
export default function Page() { return <PublicPage eyebrow="SOULSCOPE" title="Privacy notice">
<p className="lead">Your voice is personal. This notice describes the current SoulScope beta, operated by {OPERATOR}.</p><p>Last updated: {POLICY_UPDATED}</p>
<section className="panel"><h2>Information involved</h2><p>Creating an account involves an email address and authentication information. A submitted scan includes three audio recordings, recording times, and technical information needed to process it. The service saves acoustic measurements, evidence records, result records, and scan history. Support emails contain whatever you choose to send.</p><p>Recording requires microphone permission. Before submission, recordings stay on the scan page; leaving that page clears them. Record your own voice and avoid names or sensitive details about other people.</p></section>
<section className="panel"><h2>How it is used</h2><p>The service uses account information to authenticate you and provide access to your history. Submitted audio is used to check recording quality and produce acoustic records and supported recording descriptions. The current processing path does not transcribe your words or generate psychological interpretations.</p><p>Sending a scan is permission to process that scan for the service. It is not consent to a separate research study.</p></section>
<section className="panel"><h2>Storage and service providers</h2><p>Submitted audio is stored in private backend storage. Saved records are associated with your account, and account access rules restrict which records can be retrieved. Technical records are available through your signed-in results pages.</p><p>The current deployment uses Supabase for authentication, database, and private audio storage, and Vercel for hosting and server processing. Support messages sent to our Gmail address are handled through Google. These providers process data to deliver their services, and may handle technical logs such as request and connection information.</p><p>Your account uses browser storage to keep your sign-in session. This notice does not promise that technical security controls eliminate every risk.</p></section>
<section className="panel"><h2>Retention and deletion</h2><p>Automatic deletion of raw audio has not been confirmed in this beta. A cleanup helper exists, but its presence is not a guarantee that a schedule is active. Derived measurement, evidence, and result records persist separately from audio.</p><p>Final retention periods and regional requirements are still being established. Do not submit sensitive material on the assumption that it will be automatically deleted after a fixed period.</p><p>For access, correction, account closure, or deletion requests, email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. We may need to verify account ownership. We will explain any technical or applicable legal limits when handling a request; this notice does not promise immediate deletion from every backup or log.</p></section>
<section className="panel"><h2>Questions and changes</h2><p>Contact {OPERATOR} at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. We will update the date on this page when the notice changes. Regional legal terms and the retention policy require further review before the service leaves beta.</p></section>
</PublicPage>; }
