import { provenance, sourceReference } from "./provenance";

export const PATTERN_REGISTRY_VERSION = "0.1" as const;

export const PATTERN_IDS = Object.freeze([
  "PTN-S01",
  "PTN-S02",
  "PTN-S03",
  "PTN-S04",
  "PTN-S05",
  "PTN-S06",
  "PTN-S07",
] as const);

export type PatternId = (typeof PATTERN_IDS)[number];

export const PATTERN_OUTCOME_TYPES = Object.freeze([
  "PATTERN",
  "PATTERN_WITH_MODIFIER",
  "BOUNDARY_PATTERN",
  "NO_PATTERN_PUBLISHED",
  "SUPPRESSED",
  "INVALID",
] as const);

export type PatternOutcomeType = (typeof PATTERN_OUTCOME_TYPES)[number];

export const PATTERN_PUBLICATION_STATUSES = Object.freeze(["PATTERN_PUBLISHED", "NO_PATTERN_PUBLISHED"] as const);

export type PatternPublicationStatus = (typeof PATTERN_PUBLICATION_STATUSES)[number];

export const PATTERN_ABSTENTION_REASONS = Object.freeze([
  "INSUFFICIENT_CONSTELLATION_COVERAGE",
  "REQUIRED_DIMENSION_UNRESOLVED",
  "REQUIRED_INTERACTION_UNRESOLVED",
  "PATTERN_MODEL_NOT_VALIDATED",
  "PATTERN_FIT_TOO_LOW",
  "LOW_PATTERN_CONFIDENCE",
  "HIGH_CROSS_DOMAIN_CONTRADICTION",
  "MULTIPLE_PLAUSIBLE_MOTIFS",
  "NONADJACENT_COMPETING_PATTERNS",
  "INSUFFICIENT_EVIDENCE_INDEPENDENCE",
  "MODEL_OUT_OF_DISTRIBUTION",
  "ACTIVE_HARD_CONFOUND",
  "PROTOCOL_INCOMPATIBLE",
] as const);

export type PatternAbstentionReason = (typeof PATTERN_ABSTENTION_REASONS)[number];

export const PATTERN_MODIFIERS = Object.freeze([
  "GREATER_OBSERVABLE_COST",
  "LOWER_OBSERVABLE_COST",
  "HIGHER_MOBILIZATION",
  "LOWER_MOBILIZATION",
  "STRONGER_CONTEXT_SHIFT",
  "LOWER_CONTEXT_SHIFT",
  "BROADER_MODULATION",
  "NARROWER_MODULATION",
] as const);

export type PatternModifier = (typeof PATTERN_MODIFIERS)[number];

export const PATTERN_DEFINITIONS = Object.freeze({
  "PTN-S01": Object.freeze({
    patternId: "PTN-S01" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "COHERENT_MAINTENANCE",
    scientificClass: "P1_STRUCTURAL_SUMMARY",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze(["COG-P1", "COG-P3", "REG-P2", "CAP-P4"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S02", "PTN-S03"] as const),
    permittedModifiers: PATTERN_MODIFIERS,
    prohibitedMeanings: Object.freeze(["healthy", "regulated", "resilient", "optimal", "emotionally_stable", "well_adjusted", "strong_person"] as const),
    userLanguageKey: "pattern.coherent_maintenance",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S02": Object.freeze({
    patternId: "PTN-S02" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "MOBILIZED_MAINTENANCE",
    scientificClass: "P1_STRUCTURAL_SUMMARY_P2_COST_RELATIONSHIP",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze(["REG-P1", "CAP-P1", "COG-P1", "COG-P3", "CAP-P4"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S01", "PTN-S03", "PTN-S04"] as const),
    permittedModifiers: PATTERN_MODIFIERS,
    prohibitedMeanings: Object.freeze(["motivated", "excited", "determined", "energetic_personality", "high_performer"] as const),
    userLanguageKey: "pattern.mobilized_maintenance",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S03": Object.freeze({
    patternId: "PTN-S03" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "MAINTAINED_WITH_COST",
    scientificClass: "P2_COST_RELATIONSHIP",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze(["CAP-P3"] as const),
    maintainedFunctionDimensions: Object.freeze(["COG-P1", "COG-P3", "REG-P2", "CAP-P4"] as const),
    requiredStructuralConditions: Object.freeze(["MAINTAINED_FUNCTION", "INDEPENDENTLY_ELEVATED_EFFORT_COST"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S01", "PTN-S02", "PTN-S06"] as const),
    permittedModifiers: Object.freeze(["GREATER_OBSERVABLE_COST", "BROADER_MODULATION", "NARROWER_MODULATION"] as const),
    prohibitedMeanings: Object.freeze(["burnout", "hidden_stress", "masking_emotion", "exhaustion", "overworking", "pushing_through", "coping_failure"] as const),
    userLanguageKey: "pattern.maintained_with_cost",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S04": Object.freeze({
    patternId: "PTN-S04" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "CONTEXTUAL_RECONFIGURATION",
    scientificClass: "P1_STRUCTURAL_SUMMARY_P4_TEMPORAL_PATTERN",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze(["REG-P3"] as const),
    requiredStructuralConditions: Object.freeze(["EV_CONTEXT_RECONFIGURATION", "CONTEXT_SENSITIVE_CHANGE_WITH_COHERENCE"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S02", "PTN-S05", "PTN-S07"] as const),
    permittedModifiers: Object.freeze(["STRONGER_CONTEXT_SHIFT", "LOWER_CONTEXT_SHIFT", "BROADER_MODULATION", "NARROWER_MODULATION"] as const),
    prohibitedMeanings: Object.freeze(["adaptable_person", "resilient", "healthy_coping", "emotionally_flexible", "socially_skilled"] as const),
    userLanguageKey: "pattern.contextual_reconfiguration",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S05": Object.freeze({
    patternId: "PTN-S05" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "VARIABLE_RECONFIGURATION",
    scientificClass: "P3_CROSS_DOMAIN_CONFIGURATION_P4_TEMPORAL_PATTERN",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze(["REG-P2"] as const),
    requiredStructuralConditions: Object.freeze(["SUBSTANTIAL_DYN_VOLATILITY", "MEANINGFUL_MULTI_DOMAIN_MOVEMENT"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S04", "PTN-S07"] as const),
    permittedModifiers: Object.freeze(["STRONGER_CONTEXT_SHIFT", "LOWER_CONTEXT_SHIFT"] as const),
    prohibitedMeanings: Object.freeze(["emotionally_volatile", "unstable_person", "dysregulated", "erratic", "unpredictable"] as const),
    userLanguageKey: "pattern.variable_reconfiguration",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S06": Object.freeze({
    patternId: "PTN-S06" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "CROSS_DOMAIN_MISMATCH",
    scientificClass: "P3_CROSS_DOMAIN_CONFIGURATION",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze([] as const),
    requiredStructuralConditions: Object.freeze(["TWO_OR_MORE_WELL_RESOLVED_DOMAINS_DIFFERENT_DIRECTIONS", "INDEPENDENT_EVIDENCE_CHAINS"] as const),
    requiredInteractions: Object.freeze([] as const),
    adjacentPatterns: Object.freeze(["PTN-S03", "PTN-S07"] as const),
    permittedModifiers: PATTERN_MODIFIERS,
    prohibitedMeanings: Object.freeze(["inner_outer_self", "hidden_emotion", "inauthenticity", "suppression", "deception", "conflict_inside_person"] as const),
    userLanguageKey: "pattern.cross_domain_mismatch",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
  "PTN-S07": Object.freeze({
    patternId: "PTN-S07" as const,
    patternVersion: PATTERN_REGISTRY_VERSION,
    canonicalInternalName: "TEMPORAL_RELATION_SHIFT",
    scientificClass: "P4_TEMPORAL_PATTERN",
    scientificStatus: "RESEARCH_ONLY",
    requiredDimensions: Object.freeze([] as const),
    requiredInteractions: Object.freeze(["SHIFTS"] as const),
    requiredStructuralConditions: Object.freeze(["TWO_DISTINGUISHABLE_RELATION_REGIMES"] as const),
    adjacentPatterns: Object.freeze(["PTN-S04", "PTN-S05", "PTN-S06"] as const),
    permittedModifiers: Object.freeze(["STRONGER_CONTEXT_SHIFT", "LOWER_CONTEXT_SHIFT", "GREATER_OBSERVABLE_COST", "LOWER_OBSERVABLE_COST"] as const),
    prohibitedMeanings: Object.freeze(["improvement", "decline", "healing", "regression", "progress", "deterioration", "recovery"] as const),
    userLanguageKey: "pattern.temporal_relation_shift",
    activationStatus: "RESEARCH_ONLY",
    validationStatus: "CALIBRATION_REQUIRED",
  }),
});

export const PATTERN_BOUNDARY_POLICY = Object.freeze({
  registryVersion: PATTERN_REGISTRY_VERSION,
  optional: true,
  patternOccursAfterInteractions: true,
  describesScanNotPerson: true,
  forceWinner: false,
  normalizeCandidateScoresToForceWinner: false,
  defaultPublicationStatus: "NO_PATTERN_PUBLISHED" as PatternPublicationStatus,
  canonicalNoPatternReasonWhenNoCandidateClears: "NO_PATTERN_PUBLISHED",
  unresolvedRequiredConstructMakesCandidateIneligible: true,
  protocolUnobservableDimensions: Object.freeze(["REG-P4", "CAP-P2", "EXP-P4"] as const),
  protocolUnobservablePatternInferenceAllowed: false,
  boundaryPatternsRequireRegisteredAdjacency: true,
  nonadjacentCompetingPatternsOutcome: "NO_PATTERN_PUBLISHED" as PatternOutcomeType,
  nonadjacentCompetingPatternsReason: "NONADJACENT_COMPETING_PATTERNS",
  threeOrMorePlausiblePatternsOutcome: "NO_PATTERN_PUBLISHED" as PatternOutcomeType,
  threeOrMorePlausiblePatternsReason: "MULTIPLE_PLAUSIBLE_MOTIFS",
  maxPatternLevelModifiers: 1,
  missingModifierEvidenceBehavior: "OMIT_MODIFIER_DO_NOT_INFER_OPPOSITE",
  statusCannotExceedWeakestRequiredUpstream: true,
  evidenceSourceOverlapPropagatesIntoPatternConfidence: true,
  rejectedCandidatesMustRetainReasons: true,
  createsUpstreamScienceAllowed: false,
  llmCreatedPatternAllowed: false,
  narrativeMayTranslateCompletedPatternOnly: true,
  resonanceSignatureInputAllowed: false,
  prohibitedMeanings: Object.freeze([
    "personality",
    "archetype",
    "identity",
    "emotional_type",
    "diagnostic_category",
    "clinical_classification",
    "coping_style",
    "attachment_style",
    "spiritual_state",
    "hidden_truth",
    "future_behavior_prediction",
  ] as const),
  calibrationPlaceholders: Object.freeze([
    "PATTERN_CENTROIDS_CALIBRATION_REQUIRED",
    "COVARIANCE_MATRICES_CALIBRATION_REQUIRED",
    "CALIBRATED_PATTERN_REGIONS_REQUIRED",
    "FIT_THRESHOLDS_CALIBRATION_REQUIRED",
    "PUBLICATION_THRESHOLDS_CALIBRATION_REQUIRED",
    "CONFIDENCE_THRESHOLDS_CALIBRATION_REQUIRED",
    "ADJACENCY_MARGINS_CALIBRATION_REQUIRED",
    "COMPLEXITY_WEIGHTS_CALIBRATION_REQUIRED",
    "TRAINED_MODELS_CALIBRATION_REQUIRED",
    "CALIBRATION_DATASETS_REQUIRED",
  ] as const),
  provenance: provenance(sourceReference("patternRegistry", "Whole-Scan Pattern Registry v0.1", "CANON")),
});

export const PATTERN_ACCEPTANCE_TEST_IDS = Object.freeze([
  "PTN-FORCE-001",
  "PTN-UPSTREAM-001",
  "PTN-D3-001",
  "PTN-COST-001",
  "PTN-MULTI-001",
  "PTN-BLEND-001",
  "PTN-NONADJ-001",
  "PTN-MOD-001",
  "PTN-MOD-002",
  "PTN-STATUS-001",
  "PTN-LLM-001",
  "PTN-IDENTITY-001",
  "PTN-RES-001",
] as const);
