export const SCIENTIFIC_STATUSES = Object.freeze([
  "ENGINEERING_PRIOR",
  "MEASUREMENT_VERIFIED",
  "RELIABILITY_VERIFIED",
  "CONSTRUCT_VALIDATED",
  "CALIBRATED",
  "PRODUCTION_ACTIVE",
  "RESEARCH_ONLY",
  "DEPRECATED",
] as const);

export type ScientificStatus = (typeof SCIENTIFIC_STATUSES)[number];

export const RESOLUTION_STATUSES = Object.freeze([
  "RESOLVED",
  "PARTIALLY_RESOLVED",
  "UNRESOLVED",
  "SUPPRESSED",
  "INVALID",
  "RESEARCH_ESTIMATE",
] as const);

export type ResolutionStatus = (typeof RESOLUTION_STATUSES)[number];

export const RESOLUTION_REASONS = Object.freeze([
  "NO_RECOVERY_COMPATIBLE_CONDITION",
  "NO_RESERVE_COMPATIBLE_LOAD_PROTOCOL",
  "NO_RELATIONAL_OBSERVATION",
  "MISSING_REQUIRED_EVIDENCE",
  "NO_VALID_SPREAD",
  "QUALITY_GATE_FAILED",
  "CONSTRUCT_MODEL_NOT_VALIDATED",
  "NO_STATE_EXCEEDS_FIT_THRESHOLD",
  "LOW_STATE_CONFIDENCE",
  "NONADJACENT_STATE_OVERLAP",
  "MORE_THAN_TWO_PLAUSIBLE_STATES",
  "STATE_MODEL_NOT_VALIDATED",
  "PARTICIPANT_UNRESOLVED",
  "NO_PATTERN_PUBLISHED",
  "INSUFFICIENT_CONSTELLATION_COVERAGE",
  "REQUIRED_DIMENSION_UNRESOLVED",
  "REQUIRED_INTERACTION_UNRESOLVED",
  "PATTERN_MODEL_NOT_VALIDATED",
  "PATTERN_FIT_TOO_LOW",
  "LOW_PATTERN_CONFIDENCE",
  "HIGH_CROSS_DOMAIN_CONTRADICTION",
  "MULTIPLE_PLAUSIBLE_MOTIFS",
  "NONADJACENT_COMPETING_PATTERNS",
  "INSUFFICIENT_EVIDENCE_INDEPENDENCE",
  "MODEL_OUT_OF_DISTRIBUTION",
  "ACTIVE_HARD_CONFOUND",
  "PROTOCOL_INCOMPATIBLE",
  "ARCHITECTURE_VIOLATION",
] as const);

export type ResolutionReason = (typeof RESOLUTION_REASONS)[number];
