import type { Metadata } from "next";
import Link from "next/link";
import { PublicPage } from "@/components/public-page";
import { OPERATOR, SUPPORT_EMAIL, POLICY_UPDATED } from "@/lib/site";
export const metadata: Metadata = { title: 'Beta terms of service', description: 'SoulScope beta service terms, appropriate use, result limitations, and support information.', alternates: { canonical: "/terms" } };
export default function Page() { return <PublicPage eyebrow="SOULSCOPE" title="Beta terms of service">
<p className="lead">These terms describe use of the SoulScope beta, operated by {OPERATOR}.</p><p>Last updated: {POLICY_UPDATED}</p>
<section className="panel"><h2>The service</h2><p>SoulScope provides guided voice recording, saved scan history, and supported descriptions of recordings. Features may change as the service develops. Psychological interpretations and the measured Signature are not available in this release; illustrative previews are labeled.</p><p>Using the service means using it within these beta terms. If you do not agree, do not submit a scan. Read the <Link href="/privacy">privacy notice</Link> before submitting audio.</p></section>
<section className="panel"><h2>Your account and recordings</h2><p>Keep your account credentials private. Record only your own voice and material you have permission to submit. Do not impersonate others, submit recordings without permission, interfere with the service, or attempt to access another account.</p><p>Submitting a recording authorizes processing and storage needed to provide the service as described in the privacy notice. It does not authorize a separate research study.</p></section>
<section className="panel"><h2>Understanding a result</h2><p>A result describes a particular recording and may be incomplete or unavailable. Microphone position, background sound, speech style, and recording quality can affect what is observed. A result is not a diagnosis, treatment recommendation, personality assessment, or proof of an emotional cause.</p><p>Use SoulScope for self-observation. Do not use it for medical, employment, insurance, disciplinary, or other consequential decisions about a person. The service does not provide emergency help.</p></section>
<section className="panel"><h2>Availability and changes</h2><p>The beta may experience outages, processing failures, or changes in functionality. A particular result is not guaranteed. New releases may change presentation; saved scientific records are kept separate from the language used to display them.</p><p>We will update this page when the terms change. Final regional terms and retention requirements are still under review. These beta terms do not remove rights you have under applicable law.</p></section>
<section className="panel"><h2>Help and account requests</h2><p>Contact {OPERATOR} at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> for account support, questions about these terms, or account closure requests. We may need to verify account ownership.</p></section>
</PublicPage>; }
